### ISSUE TITLE
Status of https://github.com/Ethereum-community

### ISSUE THREAD

**Issue by paulvi** [Ethereum-community/homestead-guide#4]
It looks like now that whole https://github.com/Ethereum-community orgnization now is like archive of some @jamesray1 work.

And it is said stated so, so nothing needs to be done.
But some links within this or other repos can confuse.

**Comment by jamesray1** [comment]
I don't think it's worth maintaining separately forked repos to the originals in https://github.com/ethereum since they are still being maintained.

**Comment by jamesray1** [comment]
Perhaps I should delete the whole organization.

**Comment by jamesray1** [comment]
I added a deprecation notice to the title of each repo, hopefully that will be enough to avoid deletion of the whole organization.

**Comment by paulvi** [comment]
closing
